apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p5laris-lab

resources:
  - ../../base/common
  - ../../base/apps/gateway
  - ../../base/apps/user
  - ../../base/apps/mission
