apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5laris-user
  namespace: p5laris-lab
spec:
  template:
    spec:
      containers:
        - name: user
          livenessProbe:
            $patch: replace
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            $patch: replace
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
