apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: p5laris-lab

resources:
  - ../../base
  - secret.local.yaml

patches:
  - path: configmap.local.patch.yaml
  - path: db-url-patches/user-db-url.patch.yaml
  - path: db-url-patches/character-db-url.patch.yaml
  - path: db-url-patches/item-db-url.patch.yaml
  - path: db-url-patches/mission-db-url.patch.yaml
  - path: db-url-patches/event-log-db-url.patch.yaml
  - path: db-url-patches/ai-db-url.patch.yaml
  - path: db-url-patches/notification-db-url.patch.yaml
  - path: service-patches/gateway-loadbalancer.patch.yaml
