apiVersion: v1
kind: Secret
metadata:
  name: p5laris-secret
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres:5432/postgres"
  DB_USERNAME: "change-me"
  DB_PASSWORD: "change-me"

  REDIS_PASSWORD: ""

  JWT_SECRET: "change-me"
  JWT_ACCESS_EXPIRATION_MS: "3600000"
  JWT_REFRESH_EXPIRATION_MS: "1209600000"

  GOOGLE_CLIENT_ID: "change-me"
  GOOGLE_CLIENT_SECRET: "change-me"

  INTERNAL_GRPC_AUTH_TOKEN: "change-me"

  KMA_WEATHER_SERVICE_KEY: "change-me"
  ADSENSE_CLIENT_ID: ""