apiVersion: v1
kind: Service
metadata:
  name: character-service
  labels:
    app: p5laris-character
spec:
  type: ClusterIP
  selector:
    app: p5laris-character
  ports:
    - name: grpc
      port: 9092
      targetPort: 9092
    - name: http
      port: 8080
      targetPort: 8080
