apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5laris-item
spec:
  template:
    spec:
      containers:
        - name: item
          env:
            - name: DB_URL
              value: "jdbc:postgresql://host.docker.internal:5432/item"
