apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5laris-mission
spec:
  template:
    spec:
      containers:
        - name: mission
          env:
            - name: DB_URL
              value: "jdbc:postgresql://host.docker.internal:5432/mission"
