apiVersion: apps/v1
kind: Deployment
metadata:
  name: p5laris-notification
spec:
  template:
    spec:
      containers:
        - name: notification
          env:
            - name: DB_URL
              value: "jdbc:postgresql://host.docker.internal:5432/notification"
