apiVersion: v1
kind: Service
metadata:
  name: event-log-service
  labels:
    app: p5laris-event-log
spec:
  type: ClusterIP
  selector:
    app: p5laris-event-log
  ports:
    - name: grpc
      port: 9099
      targetPort: 9099
    - name: http
      port: 8080
      targetPort: 8080
