apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    app: p5laris-ai
spec:
  type: ClusterIP
  selector:
    app: p5laris-ai
  ports:
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: http
      port: 8080
      targetPort: 8080
