apiVersion: v1
kind: Service
metadata:
  name: mission-service
  labels:
    app: p5laris-mission
spec:
  type: ClusterIP
  selector:
    app: p5laris-mission
  ports:
    - name: grpc
      port: 9094
      targetPort: 9094
    - name: http
      port: 8080
      targetPort: 8080
